return {
  -- {
  --   "xiyaowong/nvim-transparent",
  --   opts = {
  --     extra_groups = {
  --       "BufferLineTabClose",
  --       "BufferlineBufferSelected",
  --       "BufferLineFill",
  --       "BufferLineBackground",
  --       "BufferLineSeparator",
  --       "BufferLineIndicatorSelected",
  --     },
  --   },
  -- },
  -- {
  --   "rcarriga/nvim-notify",
  --   opts = {
  --     background_colour = "#000000",
  --   },
  -- },
}
